version: "3"

services:
  hadoop_exporter:
    image: vqcuong96/hadoop_metric_exporter
    container_name: hadoop_metric_exporter
    ports:
      - 9123:9123
    volumes:
      - ./example/config.yaml:/exporter/config.yaml
      - exporter_logs:/exporter/logs
volumes:
  exporter_logs:
    external: false
